#include <syslog.h>
 
int main(int argc, char *argv[]){
	//写入日志(自动调用 openlog)
	syslog(LOG_ERR | LOG_USER,"test - %m\n");
	//打开日志设备
	openlog("SyslogTest",LOG_CONS | LOG_PID,0);
	//写入日志
	syslog(LOG_DEBUG,"This is a syslog test message generated by program '%s'\n",argv[0]);
	//关闭日志设备
	closelog();
	return 0;	
}


